class Consts:
    PRINT_READING = True

    ONBOARD_LED_PIN = 25
    RED_LED_PIN = 16
    GREEN_LED_PIN = 17

    ADC_PIN = 28

    UPDATE_TIME = 1
    CONVERSION_FACTOR = 3.3 / 65535
    VOLTAGE_DIVIDER_FACTOR = 11 # 1V ON ADC PIN = 11V OF SOURCE VOLTAGE
    VOLTAGE_ACCURACY = 0.5

    EXTREME_LOW_VOLTAGE_THRESHOLD = 10.8
    LOW_BATTERY_VOLTAGE_THRESHOLD = 11.2
    HIGH_BATTERY_THRESHOLD = 11.8
